info:
  name: Get default topic configuration
  type: http
  seq: 1
  tags:
    - topic

http:
  method: GET
  url: "{{baseUrl}}/api/topic/defaults-configs"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: getDefaultConf 200 response
    request:
      url: "{{baseUrl}}/api/topic/defaults-configs"
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: "{}"
